[DarwinProfile] Fix TypeError regression in debug (-d) build
As part of a recent refactoring [1] and, the GCC flags -O0
and -ggdb3 were moved to be applied directly to the
self.gcc_flags (when self.cmd_options.debug is true).

But gcc_flags' extend() method only allows 1 argument (array),
like gcc_debug_flags, not N (a-la "params" in C#).

So this commit fixes this typo, which generated an exception,
whose stacktrace can be seen in comment#2 of banshee's 750110
bgo bug ([2]):

```
$ ./darwin.py -bvd
bockbuild rev. 72fc50e
---
Traceback (most recent call last):
  File "./darwin.py", line 70, in <module>
    BansheeDarwinProfile ().build ()
  File "./darwin.py", line 13, in __init__
    DarwinProfile.__init__ (self)
  File "../../bockbuild/darwinprofile.py", line 49, in __init__
    self.gcc_flags.extend ('-O0', '-ggdb3')
TypeError: extend() takes exactly one argument (2 given)
```

[1] https://github.com/mono/bockbuild/commit/00e0e8ec65f1f0dab3814621ae752ade2e57138c
[2] https://bugzilla.gnome.org/show_bug.cgi?id=750110#c1