Revert "Bump LLVM to 0e362dce134e2234abb28465f05f0564f43b1dfb."
This reverts commit 0aa1b95f422d09135a28a7b2b52c557724dc9f5e, as it breaks the build with:

Undefined symbols for architecture i386:
  "llvm::JITDwarfEmitter::EmitDwarfTable(llvm::MachineFunction&, llvm::JITCodeEmitter&, unsigned char*, unsigned char*, unsigned char*&;)", referenced from:
      (anonymous namespace)::JITEmitter::finishFunction(llvm::MachineFunction&;) in libLLVMJIT.a(JITEmitter.o)
  "llvm::JITDwarfEmitter::JITDwarfEmitter(llvm::JIT&;)", referenced from:
      llvm::JIT::createEmitter(llvm::JIT&, llvm::JITMemoryManager*, llvm::TargetMachine&;) in libLLVMJIT.a(JITEmitter.o)
ld: symbol(s) not found for architecture i386