[msbuild] Add the missing System.Reflection.Metadata.dll required by
.. Microsoft.Tasks.Core.dll . Corresponds to the msbuild commit:

commit 95ab657a9017ea19eef8afa0d05841fdd781f363
Author: Ankit Jain <ankit.jain@xamarin.com>
Date:   Wed Feb 22 12:30:05 2017 -0500

    [mono] Restore missing `System.Reflection.Metadata.dll` required by

    .. Tasks assembly.

    A test project failed with:

    ```
    (CoreCompile target) ->
      Program.cs(10,21): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/Users/ankit/tmp/p/MqttTest/MqttTest/MqttTest.csproj]
      Program.cs(11,28): error CS0012: The type `System.IDisposable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/Users/ankit/tmp/p/MqttTest/MqttTest/MqttTest.csproj]
    ```

    .. because of a missing `System.Runtime` reference. But a subsequent build,
    succeeded. The compiler command line has the `System.Runtime` reference this
    time!

    Looking at the logs, we see ...

    ```
      Primary reference "System.Reactive.Linq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263".
          Could not find dependent files. Could not load file or assembly 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
    ```

    ... and that no dependent references were processed, which is why we didn't get
    the `System.Runtime` reference. Debugging shows that msbuild is using
    `System.Reflection` to get the assembly dependencies
    (`AssemblyInformation.ImportAssemblyDependencies`), which does succeed.

    But we subsequently try to get the `FrameworkName` via
    `Microsoft.Build.Tasks.AssemblyInformation.get_FrameworkNameAttribute`
    which uses `System.Reflection.Metadata`, at which point the runtime
    fails to find the assembly and throws a `FileNotFoundException`:

    ```
    Exception : System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
    File name: 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
      at Microsoft.Build.Tasks.AssemblyInformation.get_FrameworkNameAttribute () [0x00031] in /Users/ankit/dev/msbuild/src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs:176
      at Microsoft.Build.Tasks.AssemblyInformation.GetAssemblyMetadata (System.String path, Microsoft.Build.Shared.AssemblyNameExtension[]& dependencies, System.String[]& scatterFiles, System.Runtime.Versioning.FrameworkName& frameworkName) [0x00015] in /Users/ankit/dev/msbuild/src/XMakeTasks/AssemblyDependency/AssemblyInformation.cs:205
      at Microsoft.Build.Tasks.SystemState.GetAssemblyMetadata (System.String path, Microsoft.Build.Shared.AssemblyNameExtension[]& dependencies, System.String[]& scatterFiles, System.Runtime.Versioning.FrameworkName& frameworkName) [0x00017] in /Users/ankit/dev/msbuild/src/XMakeTasks/SystemState.cs:480
      at Microsoft.Build.Tasks.ReferenceTable.GetUnifiedAssemblyMetadata (Microsoft.Build.Tasks.Reference reference, System.Collections.Generic.IEnumerable`1[Microsoft.Build.Tasks.UnifiedAssemblyName]& unifiedDependencies, System.String[]& scatterFiles) [0x00026] in /Users/ankit/dev/msbuild/src/XMakeTasks/AssemblyDependency/ReferenceTable.cs:1006
      at Microsoft.Build.Tasks.ReferenceTable.FindDependenciesAndScatterFiles (Microsoft.Build.Tasks.Reference reference, System.Collections.ArrayList newEntries) [0x0004b] in /Users/ankit/dev/msbuild/src/XMakeTasks/AssemblyDependency/ReferenceTable.cs:1124
    ```

    ```
    Mono: The following assembly referenced from /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Microsoft.Build.Tasks.Core.dll could not be loaded:
         Assembly:   System.Reflection.Metadata    (assemblyref_index=6)
         Version:    1.3.0.0
         Public Key: b03f5f7f11d50a3a
    The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/Library/Frameworks/Mono.framework/Versions/4.8.0//lib/mono/msbuild/15.0/bin/).

    Mono: Failed to load assembly Microsoft.Build.Tasks.Core
    ```

    All the primary references get this exception while trying to get their
    dependencies, hence none of the dependencies are processed.

    The issue is that `System.Reflection.Metadata.dll` is not available. It
    was moved from the `bin` directory to `bin/Roslyn/`, but it is required
    here too.

    The second build worked because:
     - during the first build, we did get the dependencies and they were
       saved to the state file, and then retrieved in the second build.
     - we didn't need to look at get dependencies again and so, we avoided
       the earlier exception.